package com.example.hibernatedemo.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Represents a player entity within the application.
 * <p>
 * This class is mapped to the database table {@code player} and holds
 * the main identity and contact information of a system player.
 * </p>
 *
 * <p>
 * Each {@code Player} instance has a unique identifier ({@link #id}),
 * a given name, a surname, and an email address. This entity is
 * typically managed by the {@code PlayerRepository} and accessed via
 * the {@code PlayerService}.
 * </p>
 */
@Entity
public class Player {

    /**
     * Unique identifier for the player.
     * <p>
     * This value is auto-generated by the persistence provider.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The player's given name.
     */
    @NotBlank(message = "Name cannot be blank")
    @Size(max = 30, message = "Name must be at most 30 characters")
    private String name;

    /**
     * The player's family name (surname).
     */
    @NotBlank(message = "Surname cannot be blank")
    @Size(max = 30, message = "Name must be at most 30 characters")
    private String surname;

    /**
     * The player's email address.
     */
    @NotBlank(message = "Name cannot be blank")
    @Size(max = 50, message = "Name must be at most 50 characters")
    @Email(message = "Email should be valid")
    @Column(unique = true)
    private String email;

    // Constructors
    public Player() {
    }

    public Player(String name, String surname, String email) {
        this.name = name;
        this.surname = surname;
        this.email = email;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "Player {id=" + id + ", name=" + name + ", surname=" + surname + ", email=" + email + "}";
    }
}
