package com.example.hibernatedemo.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a user entity within the application.
 * <p>
 * This class is mapped to the database table {@code users} and holds
 * the main identity and contact information of a system user.
 * </p>
 *
 * <p>
 * Each {@code User} instance has a unique identifier ({@link #id}),
 * a given name, a surname, and an email address. This entity is
 * typically managed by the {@code UserRepository} and accessed via
 * the {@code UserService}.
 * </p>
 */
@Entity
@Table(name = "users") // This avoids the SQL keyword conflict
public class User {

    /**
     * Unique identifier for the user.
     * <p>
     * This value is auto-generated by the persistence provider.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The user's given name. */
    private String name;

    /** The user's family name (surname). */
    private String surname;

    /** The user's email address. */
    private String email;

    // Constructors
    public User() {
    }

    public User(String name, String surname, String email) {
        this.name = name;
        this.surname = surname;
        this.email = email;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
